version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
      NODE_ENV: "development"
      SMTP_USER: "nyirendacompany@gmail.com"
      SMTP_PASS: ""
      PREFIX: "api/"
      HOST: "0.0.0.0"
      PORT: "5000"
      JWT_SECRET: "SmztGudLFrG0yf2vGwsL/tz54lVbIIyVALZw6vQHxyHsN7eOZ2fRp2rCpBF8H0rmWcCPOJxg9suW92J6ee7Tgw=="
      JWT_REFRESH: "skCrLtDYnAGjbbHaDf9H6FLFJlsZ7YTNifjEp7rnxPaVqjRWORI7ljiXNF8fI8Lf9ChVj/WsYtqYiJGlsHMjvg=="
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  app-network: